### PR TITLE
Refactored and cleaned up most of it

### PR DESCRIPTION
**Pull request by KaiserBh**
Hi Rick,
Hope you been well, So I refactored most of the code and kinda structured the files so that it's not messy care to have a look at it and test it for me to see if everything works as intended if you have the time. Also, there is a lot of duplicate codes that I came across that still need some fixing maybe like make a function or something like that because we can cut around 200 + lines if it done properly.

### CODE REVIEW

**Comment by RickDB** [comment]
Hi Kaiser,

Thanks for the much needed refactor :)
Just let me know when the Git conflicts are resolved and will start merging it in.

Docker would also need an update but first let's test out the changes and inform current users about the config / setup changes and of course the new features via AniList / Plex thread.

**Comment by KaiserBh** [comment]
> Hi Kaiser,
> 
> Thanks for the much needed refactor :)
> Just let me know when the Git conflicts are resolved and will start merging it in.
> 
> Docker would also need an update but first let's test out the changes and inform current users about the config / setup changes and of course the new features via AniList / Plex thread.
> 
> Started as a small script and this a good step forward and next up is HAMA's AniDB matching integration (Scudlee lists etc..), still not a huge fan of Python in general compared to C# / .NET but probably still a bit of a learning curve.

No worries :) 
Done that should resolve the conflicts. 
also, did you test it out by any chance?
Because I did test it out myself but it would assure me if someone else tests it as well as I refactored quite a lot.

> next up is HAMA's AniDB matching integration (Scudlee lists etc..)
sounds fun, I had a look at the Scudlee lists and think it will be great to use it.

**Comment by RickDB** [comment]
> also, did you test it out by any chance?

Work will keep me occupied for most of the week but marked it out for this weekend :)

**Comment by KaiserBh** [comment]
Okay sounds good stay frosty and safe :)

**Comment by RickDB** [comment]
Sorry for the delay and merged in 👍

**Comment by RickDB** [comment]
Do see some Travis errors popping up and could you check them:

https://travis-ci.org/github/RickDB/PlexAniSync

Readme had a merge error which I noticed before but corrected (seems to be unchanged).

**Comment by KaiserBh** [comment]
All good Rick, also I am assuming you checked it and tested it yea? Cause I found something interesting when I was playing with it. but could be my system, I can't seem to run it from cmd, or console probably because of the pathing issues. 

If you checked it and no issues in your end then should be good.

**Comment by RickDB** [comment]
Thanks :)

Getting the same path issues with todays test but also some out of sync files like readme missing new config explanation, if you could check those out would be great.

**Comment by KaiserBh** [comment]
Okay seem like I fixed the issue regarding the paths, I will do PR. also

**Pull request merged**
