### PR TITLE
[FEATURE] Added automatic loading custom_mapping.yaml from web/github

### PR DESCRIPTION
**Pull request by KaiserBh**
Hi @reconman @RickDB, Added the option to load custom mappings and updates it automatically using the community mappings. If any of you can test it, would be appreciated it. 
Also did tiny refactor. 

#94

### CODE REVIEW

**Comment by reconman** [comment]
There are two drawbacks to your current solution:
- Users have to specify yet another environment variable
- Users can't extend the mapping from the internet. My plan is to have the URL as part of the mappings YAML. First check for any URLs and add them to the custom_mappings `dict`. Then add the local ones and override remote ones if a series is defined in both.

**Comment by KaiserBh** [comment]
> There are two drawbacks to your current solution:
> 
> * Users can't extend the mapping from the internet. My plan is to have the URL as part of the mappings YAML. First check for any URLs and add them to the custom_mappings `dict`. Then add the local ones and override remote ones if a series is defined in both.

Hmm, so basically the users will have a section in the custom_mappings.yaml with section called URL? and then the users can just add any url then, get the urls and put it into a dict; go through it? 

Also can you please elaborate more on this,
> Then add the local ones and override remote ones if a series is defined in both.

The way I see it, is that we basically compare the remote and local mappings and not modifying the local ones? as in instead of writing the data from remote one as I have done, we don't touch the local one and instead just get more data from remote one and append it?

**Comment by KaiserBh** [comment]
Need this to be reviewed and tested.

**Comment by reconman** [comment]
Replaced by #111

**Pull request closed without merging**
