### PR TITLE
CLI Support and Notifications feature.

### PR DESCRIPTION
**Pull request by KaiserBh**
Added many changes.

* One of many new features is the ability to push notifications using webhook by apprise to discord and other services that apprise supports such as discord webhook etc, then there is slack and pushover support as well.

* Added better logging class with greater information that logs into a file every2 MB max 5 files by default.

* Added CLI Click option interactive command line supports such as using parameters etc.

* Added better configuration not using setting.ini anymore but instead config.json since can manipulate data easier using a config class in the misc folder.

* Updated README.md

* Revert back the logger = logging.getLogger(__name__) to the class plexmodule.py and anilist.py

* Checked --config parameter seems to be working when invoking it directly without any command such as `python ./PlexAniSync.py --config PATH plex -c direct --sync-now --notifications` this will use a specified config file.

### CODE REVIEW

**Comment by RickDB** [comment]
Thanks, will make some time this weekend to review and test this further :)

**Comment by KaiserBh** [comment]
> Thanks, will make some time this weekend to review and test this further :)

No problem, going to work on it further and set up Tautulli to work with the new config file.

**Comment by RickDB** [comment]
Looks good and gonna merge to dev this weekend, will markup up some migration steps for current users and update the docker config somewhere next week to make it ready for general release.
Thanks again for your work on this!

**Comment by KaiserBh** [comment]
No worries at all thank you for making a great tool, to begin with. Also, I haven't worked much on Tautulli support since I was thinking of real-time syncing with Tautulli, for example, it listens to Tautulli events and if this particular user is watching an anime show or any shows in general and if the user has watched around 80% of watch time get the show name and try to sync it with Anilist, but will do that sometime after my uni assignments xD got so much to do hopefully within next week or 2 I should be able to start finger cross.

**Pull request merged**
