### PR TITLE
Default Logs

### PR DESCRIPTION
**Pull request by KaiserBh**
Added small change to create a default log file into the current directory with a file name PlexAniSync.log with a default log level of INFO.

### CODE REVIEW

**Comment by RickDB** [comment]
Nice addition, my only concern is log size over time as the default Python logging function seems to lack that.
Wondering if we can add this in with a 10 megabyte limit or so:

https://stackoverflow.com/a/39442697

**Comment by KaiserBh** [comment]
Well, I can think 2 possible solution for that, one is the rotating logs like you stated the other one instead of appending can just write it again. so something like this
```
import logging
LOG_FILENAME = 'example.log'
logging.basicConfig(filename=LOG_FILENAME,level=logging.DEBUG,filemode='w')
logging.debug('This message should go to the log file GOnna append? DOubt')
```

with the filemode='w' it's pretty much writing into a fresh file.

**Comment by KaiserBh** [comment]
Alright, I have updated it now, so it will have the rotating logs after 10mb threshold it will create another log up to 5 maximum logs at any time then rotates it. Also created a separate Full DEBUG file that will pretty much give us the root level of DEBUG since I didn't see any manual input of .debug spent hours wondering why the `setLevel(logging.DEBUG)` is not working xD until I realised that there wasn't any manual debug log only .warning and .info :).

P.S I had a log file that ended up with 99GB thanks to nzbget :P

**Comment by RickDB** [comment]
Looks good and merging :)

Thanks a lot for this as it will surely help with debugging issues / tracking matches and yeah nzbget has its quirks but beats sabnzbd any day :D

**Pull request merged**
