### PR TITLE
Support for splitting seasons

### LINKED ISSUE #43: Mapping for split seasons
Re:Zero's TVDB entry has 2 seasons listed. Season 2 has 2 associated Anilist entries, https://anilist.co/anime/108632/ReZero-kara-Hajimeru-Isekai-Seikatsu-2nd-Season/ and https://anilist.co/anime/119661/ReZero-kara-Hajimeru-Isekai-Seikatsu-2nd-Season-Part-2/.

This also affects Space Dandy and Yuukoku no Moriarty.

Any ideas on how this could be solved?

### PR DESCRIPTION
**Pull request by reconman**
Fixes #43 

I also went ahead and replaced the outdated `%s` logger messages with f-strings: https://realpython.com/python-f-strings/

In my own tests, I encountered no errors or unexpected updates for 123 series in my Plex anime library.

### CODE REVIEW

**Comment by Soitora** [comment]
Maybe in the future the program could be used alongside with other tracker, in that case maybe "`animeid`" could be replace with "`anilist`"

**Comment by Soitora** [comment]
Also, maybe not the scope for this PR but, how would I go about the season 1-4 here? (TheTVDB based)

The first 4 seasons on TheTVDB is 50~ eps each while on AniList the entry is ~200 episodes. I think this is a rare case and would have a hard solution to reach 🤔 

```yaml
  - title: "Gintama"
    seasons:
      - season: 1
        animeid: 918
      - season: 2
        animeid: 918
      - season: 3
        animeid: 918
      - season: 4
        animeid: 918
      - season: 5
        animeid: 9969
      - season: 6
        animeid: 15417
      - season: 7
        animeid: 20996
      - season: 8
        animeid: 97889
      - season: 9
        animeid: 99714
      - season: 10
        animeid: 100784
        start: 1
      - season: 10
        animeid: 101925
        start: 13
```

**Comment by reconman** [comment]
@Soitora I stumbled across the code responsible for that and I couldn't come up with a good solution, so I left it as it is. Here's the relevant code: https://github.com/RickDB/PlexAniSync/blob/master/anilist.py#L647

If there are multiple seasons with the same mapped id, it just assumes that ALL seasons belong to the same anilist entry and calculates the sum of watched episodes.

**Comment by Soitora** [comment]
> If there are multiple seasons with the same mapped id, it just assumes that ALL seasons belong to the same anilist entry and calculates the sum of watched episodes.

Actually that does sound like an pretty good "easy" solution for it, in this case it's an acceptable compromise that will still keep it working correctly! 👍🏻

**Comment by reconman** [comment]
The only problem is that seasons 5 and up are ignored right now.

**Comment by reconman** [comment]
I just tried out your case and it works! 🥳

**Comment by RickDB** [comment]
Great work!

Just let me know if it's ready and will merge it in 👍🏻

**Comment by reconman** [comment]
It's already ready, I can't request your review because I'm not a collaborator (I think)

**Comment by RickDB** [comment]
Invite send for collaborator, if you have any more improvements feel free to add 🙂
Merging this in now.

**Pull request merged**
